development:
  FACEBOOK_APP_ID: "817612895098686"
  FACEBOOK_APP_SECRET: "5bb3645bb6fbe5fed135d8e0573d6570"

  GOOGLE_CLIENT_ID: "286943252279-hh6impcdusrj68ljruj2d56gs9fa34m1.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "kXx0GeLGpzU5u9GLbXDo67IT"

  TWITTER_KEY: "6v9c0t1fzmXko35RfRQzCgFGv"
  TWITTER_SECRET: "LYlW47wawBEmTEZ70PgZrTk2AtG8dTzVVwu8gafYcUtVDodmvn"